/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Ayanamsa value in degrees by integer ID.
 * ayanamsa_id: 0=Lahiri, 1=KP, ..., 16=LahiriVP285.
 */
export declare function ayanamsaById(jdUt1: number, ayanamsaId: number): number

/**
 * Delta-T in seconds (TT - UT1) at the given Julian Day using the
 * Stephenson-Morrison-Hohenkerk 2016 model.
 */
export declare function deltaT(jd: number): number

/**
 * Numerology expression number from full name.
 * `system` is "pythagorean" or "chaldean".
 */
export declare function expressionNumber(name: string, system: string): number

/**
 * Fixed-star conjunctions within `orb` degrees of `planet_lon` (degrees),
 * precessed to `year`. Returns a JSON array of { name, distance, constellation, magnitude }.
 */
export declare function fixedStarConjunctions(planetLon: number, orb: number, year: number): any

/**
 * Full sidereal chart as a JSON object — the one-contract counterpart to the
 * Python `full_chart()` and WASM `fullChartJson()`.
 *
 * Computes sidereal positions for every Vedic graha (with nakshatra, pada,
 * rashi and nakshatra lord per planet), adds Ketu as Rahu+180, and Whole-Sign
 * house cusps with the ascendant/MC and the ayanamsa used.
 *
 * `jd` is Julian Day (UT1); `lat`/`lon` are degrees; `ayanamsa_id` selects the
 * ayanamsa (0=Lahiri). Returns:
 * `{ planets: { Sun: { longitude, nakshatra, pada, rashi, lord }, ... },
 *    ascendant, mc, ayanamsaDeg, cusps: [12] }`.
 */
export declare function fullChart(jd: number, lat: number, lon: number, ayanamsaId: number): any

/**
 * Compute houses for a given Julian Day (UT1), geographic latitude/longitude in
 * degrees, and house system name. Returns an object with the 12 cusps plus the
 * Ascendant, MC, IC, Descendant and Vertex (all degrees), and `fallbackUsed`
 * (true when a polar latitude forced the Porphyry fallback). This mirrors the
 * Python binding — earlier versions returned only the 12 cusps and silently
 * dropped the angles.
 */
export declare function houses(jd: number, lat: number, lon: number, system: string): any

/**
 * Compute house cusps by integer house system ID.
 * system_id: 0=WholeSign, 1=Equal, 2=Placidus, 3=Koch, ..., 13=Krusinski.
 */
export declare function housesById(jd: number, lat: number, lon: number, systemId: number): Array<number>

/** Numerology life-path number from birth date. */
export declare function lifePath(year: number, month: number, day: number): number

/**
 * Nakshatra name for a given sidereal longitude in degrees.
 *
 * Returns just the name (e.g. `"Ashwini"`). For the full structured shape that
 * matches the Python/WASM bindings, use [`nakshatra_info`].
 */
export declare function nakshatra(siderealLon: number): string

/**
 * Full structured nakshatra detail for a sidereal longitude in degrees:
 * `{ name, pada, lord, deity, index }`. This is the one-contract counterpart to
 * the Python `nakshatra()` dict and the WASM `nakshatraInfoJson()`; the bare
 * [`nakshatra`] string function is retained for backward compatibility.
 */
export declare function nakshatraInfo(siderealLon: number): NakshatraInfo

/**
 * Structured nakshatra detail — the unified shape shared with the Python
 * (`xalen.nakshatra`) and WASM (`nakshatraInfoJson`) bindings.
 */
export interface NakshatraInfo {
  name: string
  pada: number
  lord: string
  deity: string
  index: number
}

/**
 * Panchang (tithi, nakshatra, yoga, karana, vara) as a JSON object.
 *
 * `sun_lon` and `moon_lon` are sidereal longitudes in degrees.
 * `jd` is the Julian Day (UT1).
 */
export declare function panchang(sunLon: number, moonLon: number, jd: number): any

/** Tropical (geometric) ecliptic longitude in degrees for `body` at `jd_ut1`. */
export declare function planetLongitude(body: string, jdUt1: number): number

/**
 * Tropical ecliptic longitude by integer body ID.
 * body_id: 0=Sun, 1=Moon, 2=Mercury, 3=Venus, 4=Mars, 5=Jupiter, 6=Saturn,
 *          7=Uranus, 8=Neptune, 9=Rahu, 10=TrueNode, 11=Pluto, 12=Chiron,
 *          13=Ketu (Rahu+180).
 */
export declare function planetLongitudeById(bodyId: number, jdUt1: number): number

/**
 * Full geocentric position of `body` (string name) at `jd_ut1`.
 *
 * Returns `{ longitude, latitude, distance, lonSpeed, latSpeed, distSpeed,
 * isRetrograde }` — the pyswisseph `swe.calc_ut(..., FLG_SPEED)` 6-tuple plus a
 * retrograde flag. This is the high-fidelity counterpart to
 * `planetLongitude`, which discards everything but longitude.
 */
export declare function planetPosition(body: string, jdUt1: number): PlanetPosition

/**
 * The full geocentric state of a body: the six components pyswisseph returns
 * from `swe.calc_ut(..., FLG_SPEED)` plus a retrograde flag. Speeds are daily
 * motion: degrees/day for longitude/latitude, AU/day for distance. `longitude`
 * is wrapped to [0, 360); `isRetrograde` is taken from the **tropical**
 * longitude rate (subtracting a slowly-precessing ayanamsa never flips it).
 */
export interface PlanetPosition {
  longitude: number
  latitude: number
  distance: number
  lonSpeed: number
  latSpeed: number
  distSpeed: number
  isRetrograde: boolean
}

/**
 * Full geocentric position by integer body ID. Tropical when `ayanamsa_id` is
 * `null`/`undefined`; sidereal (tropical − ayanamsa) when a valid ayanamsa ID is
 * supplied. Ketu (id 13) = Rahu + 180°, sharing Rahu's speed/retrograde state.
 *
 * body_id: 0=Sun .. 12=Chiron, 13=Ketu (Rahu+180).
 */
export declare function planetPositionById(bodyId: number, jdUt1: number, ayanamsaId?: number | undefined | null): PlanetPosition

/** Rashi (sidereal zodiac sign) name for a given sidereal longitude in degrees. */
export declare function rashi(siderealLon: number): string

/**
 * Sidereal ecliptic longitude in degrees for `body` at `jd_ut1` using the
 * named `ayanamsa` system (e.g. "lahiri", "kp", "raman").
 */
export declare function siderealLongitude(body: string, jdUt1: number, ayanamsa: string): number

/** Sidereal ecliptic longitude by integer body and ayanamsa IDs. */
export declare function siderealLongitudeById(bodyId: number, jdUt1: number, ayanamsaId: number): number
