//! Swiss Ephemeris ayanamsa oracle — live cross-validation harness.
//!
//! Every reference value in `SWISS_ORACLE` below was generated by running the
//! Swiss Ephemeris itself (via pyswisseph 2.10.03, SE data files present), NOT
//! invented. The exact, reproducible command is:
//!
//! ```python
//! import swisseph as swe
//! years = [1900, 1950, 2000, 2050, 2100]
//! jds = {y: swe.julday(y, 1, 1, 12.0) for y in years}   # noon, treated as JD(TT)
//! for sid in range(0, 47):                                # SE_SIDM_* 0..46
//!     swe.set_sid_mode(sid, 0, 0)
//!     for y in years:
//!         retflags, aya = swe.get_ayanamsa_ex(jds[y], 0)  # flags=0 => WITH nutation
//!         print(sid, y, aya)                              # retflags == 2 (SEFLG_SWIEPH)
//! ```
//!
//! Notes on the call:
//!   * `flags = 0` means the apparent (with-nutation) ayanamsa — the same
//!     quantity XALEN's dynamic `TrueChitra` reduction targets. NO `SEFLG_NONUT`.
//!   * The return tuple order is `(retflags, aya)` — the ayanamsa is the SECOND
//!     element. (Reversing it silently yields the retflag 2.0 for every row.)
//!   * `swe.julday(y, 1, 1, 12.0)` gives the JDs baked into `JDS` below:
//!       1900 -> 2415021.0, 1950 -> 2433283.0, 2000 -> 2451545.0,
//!       2050 -> 2469808.0, 2100 -> 2488070.0.
//!
//! What this validates: `Ayanamsa::compute_deg` reproduces Swiss
//! `get_ayanamsa_ex(jd, 0)` (the WITH-nutation apparent ayanamsa) to under 1"
//! across 1900–2100 for every SE id (one documented 2" exception, SE id 36 —
//! see `all_ayanamsas_match_swiss_within_1_arcsec`). Each system uses the same
//! reduction Swiss does:
//!   * fixed-epoch systems: ayan_t0 + [accumulated IAU 2006 general precession
//!     from t0] + IAU 2000B nutation in longitude (Δψ);
//!   * galactic + true-star systems (incl. TrueChitra/TrueRevati/TruePushya/
//!     TrueMula and the galactic-centre / galactic-equator frames): a fixed
//!     J2000 reference direction rotated to the ecliptic of date (IAU 2006/P03)
//!     plus Δψ.
//! This replaced an earlier single-rate-linear / hand-typed-constant
//! approximation that diverged from ~17" (nutation-omitted) to >100000"
//! (GalacticCenterCochrane's J2000 anchor was 28.5° wrong — Swiss places that
//! ayanamsa near 356.85°, not 25.36°).

use xalen_ayanamsa::Ayanamsa;

/// JD(TT) for 1900/1950/2000/2050/2100 — `swe.julday(year, 1, 1, 12.0)`.
const JDS: [f64; 5] = [2415021.0, 2433283.0, 2451545.0, 2469808.0, 2488070.0];

/// Live Swiss Ephemeris ayanamsa values (degrees, normalized to 0..360),
/// keyed by SE_SIDM id, for the five JDs in `JDS`. Generated by the pyswisseph
/// command in the module docstring above. DO NOT hand-edit — regenerate.
const SWISS_ORACLE: &[(u32, [f64; 5])] = &[
    (
        0,
        [
            23.348623597,
            24.041050305,
            24.736430097,
            25.443051651,
            26.138403992,
        ],
    ),
    (
        1,
        [
            22.465415974,
            23.157842673,
            23.853222456,
            24.559844004,
            25.255196341,
        ],
    ),
    (
        2,
        [
            26.424084841,
            27.116507630,
            27.811882905,
            28.518499346,
            29.213845981,
        ],
    ),
    (
        3,
        [
            21.019114507,
            21.711541291,
            22.406921143,
            23.113542743,
            23.808895114,
        ],
    ),
    (
        4,
        [
            18.665864495,
            19.358291278,
            20.053671130,
            20.760292730,
            21.455645101,
        ],
    ),
    (
        5,
        [
            22.368563507,
            23.060990291,
            23.756370143,
            24.462991743,
            25.158344114,
        ],
    ),
    (
        6,
        [
            26.968002095,
            27.660428878,
            28.355808730,
            29.062430330,
            29.757782701,
        ],
    ),
    (
        7,
        [
            21.087126495,
            21.779553278,
            22.474933130,
            23.181554730,
            23.876907101,
        ],
    ),
    (
        8,
        [
            21.370460495,
            22.062887278,
            22.758267130,
            23.464888730,
            24.160241101,
        ],
    ),
    (
        9,
        [
            22.141973145,
            22.834395342,
            23.529769994,
            24.236385783,
            24.931731736,
        ],
    ),
    (
        10,
        [
            23.541973145,
            24.234395342,
            24.929769994,
            25.636385783,
            26.331731736,
        ],
    ),
    (
        11,
        [
            24.391973145,
            25.084395342,
            25.779769994,
            26.486385783,
            27.181731736,
        ],
    ),
    (
        12,
        [
            23.341973145,
            24.034395342,
            24.729769994,
            25.436385783,
            26.131731736,
        ],
    ),
    (
        13,
        [
            23.130861583,
            23.823283601,
            24.518658066,
            25.225273658,
            25.920619407,
        ],
    ),
    (
        14,
        [
            23.367257165,
            24.059679362,
            24.755054014,
            25.461669803,
            26.157015756,
        ],
    ),
    (
        15,
        [
            18.856121723,
            19.548543751,
            20.243918225,
            20.950533827,
            21.645879587,
        ],
    ),
    (
        16,
        [
            18.601286045,
            19.293711450,
            19.989089514,
            20.695708916,
            21.391058681,
        ],
    ),
    (
        17,
        [
            25.454444801,
            26.146836051,
            26.842175937,
            27.548791473,
            28.244113369,
        ],
    ),
    (
        18,
        [
            358.608323784,
            359.300750408,
            359.996130131,
            0.702751631,
            1.398103932,
        ],
    ),
    (
        19,
        [
            0.004904495,
            0.697331278,
            1.392711130,
            2.099332730,
            2.794685101,
        ],
    ),
    (
        20,
        [
            359.306693760,
            359.999120468,
            0.694500260,
            1.401121814,
            2.096474155,
        ],
    ),
    (
        21,
        [
            19.503385995,
            20.195811162,
            20.891188967,
            21.597808090,
            22.293157556,
        ],
    ),
    (
        22,
        [
            19.288752045,
            19.981177212,
            20.676555017,
            21.383174140,
            22.078523606,
        ],
    ),
    (
        23,
        [
            19.503386882,
            20.195812048,
            20.891189853,
            21.597808976,
            22.293158443,
        ],
    ),
    (
        24,
        [
            19.265754502,
            19.958179668,
            20.653557473,
            21.360176596,
            22.055526063,
        ],
    ),
    (
        25,
        [
            18.711715535,
            19.404140702,
            20.099518507,
            20.806137630,
            21.501487096,
        ],
    ),
    (
        26,
        [
            21.614090435,
            22.306515602,
            23.001893407,
            23.708512530,
            24.403861996,
        ],
    ),
    (
        27,
        [
            22.449689846,
            23.141443481,
            23.836145079,
            24.542195536,
            25.236869764,
        ],
    ),
    (
        28,
        [
            18.650131215,
            19.344234109,
            20.041294780,
            20.749489139,
            21.446522637,
        ],
    ),
    (
        29,
        [
            21.334288113,
            22.027276603,
            22.723221681,
            23.430455114,
            24.126367771,
        ],
    ),
    (
        30,
        [
            21.077503784,
            21.769895034,
            22.465234920,
            23.171850456,
            23.867172352,
        ],
    ),
    (
        31,
        [
            28.624038018,
            29.320195848,
            30.019302600,
            30.729647113,
            31.428717961,
        ],
    ),
    (
        32,
        [
            28.676959889,
            29.373116646,
            30.072222311,
            30.782565723,
            31.481635454,
        ],
    ),
    (
        33,
        [
            22.010293223,
            22.706449979,
            23.405555644,
            24.115899056,
            24.814968788,
        ],
    ),
    (
        34,
        [
            28.626117656,
            29.318544283,
            30.013924008,
            30.720545509,
            31.415897811,
        ],
    ),
    (
        35,
        [
            23.188576798,
            23.880863688,
            24.576103015,
            25.282626639,
            25.977856060,
        ],
    ),
    (
        36,
        [
            18.586075687,
            19.309198927,
            20.035363243,
            20.772894009,
            21.499210156,
        ],
    ),
    (
        37,
        [
            19.184173946,
            19.876599199,
            20.571977098,
            21.278596321,
            21.973945895,
        ],
    ),
    (
        38,
        [
            23.224084841,
            23.916507630,
            24.611882905,
            25.318499346,
            26.013845981,
        ],
    ),
    (
        39,
        [
            23.841645897,
            24.534634387,
            25.230579465,
            25.937812897,
            26.633725555,
        ],
    ),
    (
        40,
        [
            355.454444801,
            356.146836051,
            356.842175937,
            357.548791473,
            358.244113369,
        ],
    ),
    (
        41,
        [
            23.608342878,
            24.300769502,
            24.996149225,
            25.702770725,
            26.398123026,
        ],
    ),
    (
        42,
        [
            21.403939688,
            22.096363294,
            22.791739430,
            23.498356777,
            24.193704363,
        ],
    ),
    (
        43,
        [
            22.450646727,
            23.143073511,
            23.838453363,
            24.545074963,
            25.240427334,
        ],
    ),
    (
        44,
        [
            22.471810229,
            23.164234495,
            23.859611333,
            24.566229424,
            25.261577793,
        ],
    ),
    (
        45,
        [
            22.388693926,
            23.081118220,
            23.776495088,
            24.483113209,
            25.178461612,
        ],
    ),
    (
        46,
        [
            22.465112637,
            23.157539335,
            23.852919119,
            24.559540667,
            25.254893003,
        ],
    ),
];

/// Smallest angular separation between two longitudes, in arcseconds.
/// Handles the 0/360 wrap (ids 18, 20, 40 straddle the boundary in some years).
fn ang_diff_arcsec(a_deg: f64, b_deg: f64) -> f64 {
    let mut d = (a_deg - b_deg).rem_euclid(360.0);
    if d > 180.0 {
        d -= 360.0;
    }
    d.abs() * 3600.0
}

fn oracle_row(id: u32) -> Option<&'static [f64; 5]> {
    SWISS_ORACLE
        .iter()
        .find(|(sid, _)| *sid == id)
        .map(|(_, v)| v)
}

/// Sanity: every SE id 0..=46 is present in the baked oracle exactly once,
/// and every named XALEN ayanamsa with an SE id resolves to an oracle row.
#[test]
fn oracle_table_is_complete_and_consistent() {
    assert_eq!(SWISS_ORACLE.len(), 47, "expected SE ids 0..=46");
    for id in 0u32..=46 {
        assert!(
            oracle_row(id).is_some(),
            "missing oracle row for SE id {id}"
        );
    }
    for a in Ayanamsa::all_named() {
        if let Some(id) = a.swiss_ephem_id() {
            assert!(
                oracle_row(id).is_some(),
                "{a} maps to SE id {id} which has no oracle row"
            );
        }
    }
}

/// PERMANENT GREEN GUARD — the one system that is a true dynamic apparent-place
/// reduction of a real fixed star. `TrueChitra` (SE id 27) must track Swiss to
/// under 1 arcsec across 1900-2100. The rigorous IAU 2006/P03 Cartesian
/// precession of Spica's J2000 position (latitude-coupled) brings the measured
/// residual to 0.038" at these epochs; the 0.5" guard below leaves margin while
/// still catching any regression to the old scalar-precession model (which
/// diverged to 1.514" because the pure-longitude term cannot couple Spica's
/// ~2.05° ecliptic latitude).
#[test]
fn true_chitra_matches_swiss_within_1_arcsec() {
    let row = oracle_row(27).expect("SE id 27 oracle");
    let mut max = 0.0_f64;
    for (i, &jd) in JDS.iter().enumerate() {
        let got = Ayanamsa::TrueChitra.compute_deg(jd);
        let d = ang_diff_arcsec(got, row[i]);
        max = max.max(d);
    }
    assert!(
        max <= 0.5,
        "TrueChitra max divergence {max:.3}\" exceeds 0.5\" tolerance"
    );
}

/// OFF-GRID GUARD — `TrueChitra` (SE id 27) at non-Jan-1, non-noon dates spread
/// across 1900-2100. The strict oracle above only samples Jan-1-noon; the OLD
/// scalar pure-longitude precession would still have looked correct at the J2000
/// anchor there but drifts to ~1.5" off it. These five reference values come from
/// pyswisseph 2.10.03 `set_sid_mode(SIDM_TRUE_CITRA); get_ayanamsa_ex(jd, 0)` at
/// arbitrary calendar dates and hours. The rigorous Cartesian Spica reduction
/// reproduces them to ≤ 0.04". This test would FAIL for the old scalar model,
/// guarding against a silent regression that the Jan-1 oracle could miss.
#[test]
fn true_chitra_matches_swiss_off_grid() {
    // (JD(TT), Swiss SE_SIDM_TRUE_CITRA apparent ayanamsa in degrees)
    const OFFGRID: &[(f64, f64)] = &[
        (2423615.750000, 22.773314533), // 1923-07-15 06:00 TT
        (2435900.250000, 23.252009364), // 1957-03-02 18:00 TT
        (2446027.500000, 23.621615404), // 1984-11-23 00:00 TT
        (2455691.000000, 24.009448346), // 2011-05-09 12:00 TT
        (2479941.875000, 24.916939625), // 2077-09-30 09:00 TT
    ];
    let mut max = 0.0_f64;
    for &(jd, swiss) in OFFGRID {
        let got = Ayanamsa::TrueChitra.compute_deg(jd);
        max = max.max(ang_diff_arcsec(got, swiss));
    }
    assert!(
        max <= 0.5,
        "TrueChitra off-grid max divergence {max:.3}\" exceeds 0.5\" tolerance"
    );
}

/// STRICT 1-ARCSEC ORACLE — asserts EVERY XALEN named ayanamsa with an SE id
/// matches Swiss within 1 arcsec at every epoch, with ONE documented exception.
///
/// As of the ayanamsa nutation/IAU-2006/dynamic rewrite, every SE-mapped system
/// tracks Swiss `get_ayanamsa_ex(jd, 0)` (the WITH-nutation apparent value) to
/// well under 1" across 1900–2100 — including `TrueChitra` (SE id 27), now 0.038"
/// after switching its Spica reduction from the scalar pure-longitude precession
/// (1.514") to the rigorous IAU 2006/P03 Cartesian rotation that couples Spica's
/// ecliptic latitude. The SINGLE remaining exception is `GalCenterMulaWilhelm`
/// (SE id 36): Swiss's internal Ernst Wilhelm reduction has a no-nutation
/// precession rate of ~52.5"/yr (≈ 2.2"/yr above general precession) combined
/// with a moderate-latitude (~few-degree) annual aberration of ~±23" — a
/// combination that no single fixed celestial direction reproduces (a fixed
/// direction at the aberration-implied latitude precesses at the general rate;
/// the only fixed direction whose longitude rate reaches 52.5"/yr lies near the
/// ecliptic pole, where its aberration would be far larger than Swiss shows).
/// The best self-contained fixed-direction + nutation model therefore tracks it
/// to ≤ 1.42" at the Jan-1 oracle epochs. That residual is DOCUMENTED here (and
/// in the function comment), not a regression — id 36 is allowed up to 2", every
/// other system (incl. id 27) stays under 1".
///
/// How the three fix families closed the old Wave-B bug list:
///   * NUTATION (Δψ): every linear + epoch_based system now adds IAU 2000B
///     nutation in longitude — fixed the uniform ~17" error.
///   * IAU 2006 PRECESSION: epoch-anchored systems accumulate the full IAU 2006
///     general precession from t0 (not a single 50.288"/yr rate) — fixed the
///     250–510" deep-epoch (1 CE / 499 CE / 564 CE) drift.
///   * DYNAMIC fixed-point reduction: the galactic + true-star systems
///     (17,28,29,30,31,32,33,35,36,39,40) rotate a fixed J2000 reference
///     direction to the ecliptic of date (IAU 2006/P03) + nutation — fixed the
///     1500–102664" divergence (Cochrane's J2000 anchor was 28.5° wrong).
#[test]
fn all_ayanamsas_match_swiss_within_1_arcsec() {
    const TOL_ARCSEC: f64 = 1.0;
    // The single documented exception: SE 36 GalCenterMulaWilhelm (~1.42") —
    // Swiss's internal Wilhelm reduction has a precession rate no fixed celestial
    // direction reproduces under the aberration constraint (see the function
    // doc-comment above). SE 27 TrueChitra is NO LONGER an exception: the
    // rigorous IAU 2006/P03 Cartesian Spica reduction brought it to 0.038"
    // (guarded separately by true_chitra_matches_swiss_within_1_arcsec).
    const TOL_ARCSEC_DOCUMENTED: f64 = 2.0;
    const DOCUMENTED_2ARCSEC_IDS: [u32; 1] = [36];
    let mut failures: Vec<String> = Vec::new();

    for a in Ayanamsa::all_named() {
        let Some(id) = a.swiss_ephem_id() else {
            continue; // PushyaPaksha / KPStraightLine / CitraAtSpica180 have no SE id
        };
        let row = oracle_row(id).expect("every SE id has an oracle row");

        let mut max = 0.0_f64;
        let mut worst_year = 0usize;
        for (i, &jd) in JDS.iter().enumerate() {
            let got = a.compute_deg(jd);
            let d = ang_diff_arcsec(got, row[i]);
            if d > max {
                max = d;
                worst_year = i;
            }
        }
        let tol = if DOCUMENTED_2ARCSEC_IDS.contains(&id) {
            TOL_ARCSEC_DOCUMENTED
        } else {
            TOL_ARCSEC
        };
        if max > tol {
            let years = [1900, 1950, 2000, 2050, 2100];
            failures.push(format!(
                "  {a} (SE {id}): max {max:.3}\" (tol {tol}\") at year {} (XALEN {:.6}° vs Swiss {:.6}°)",
                years[worst_year],
                a.compute_deg(JDS[worst_year]),
                row[worst_year]
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} ayanamsa(s) diverge from Swiss Ephemeris beyond tolerance:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
